server:
  port: 86
  session-timeout: 1800
spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/whale?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 1234
  thymeleaf:
    mode: HTML
    cache: false
  mvc:
    static-path-pattern: /**
mybatis:
  mapper-locations: mybatis/**/*Mapper.xml
logging:
  level:
    root: info
    com.lcydl: debug
