server:
  port: 86
  session-timeout: 1800
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/whale?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 1234
  thymeleaf:
    mode: HTML
    cache: false
  mvc:
    static-path-pattern: /**
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: com/lcydl/whale/common/mapper/*Mapper.xml
  typeAliasesPackage: com.lcydl.whale.common.mapper

